[package]
name = "ENSResolver"
version = "1.0.0"
authors = []

[addresses]
sender = "0xe5bf58bbf89ee015ab9941b8b376d0ce6bcf8824423febfbbbb4693cdf8f975a"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
