[package]
name = "ENSResolver"
version = "1.0.0"
authors = []

[addresses]
sender = "0xff764de1cddd35601ba7bf58c82efb89b98485939d3a470477c97993da918a26"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
